site_name: Documentation
site_url: https://karthick-somasundaresan.github.io/testdeployment/
nav:
    - 'Interface doc': 
        - 'AVSControllerAPI': 'AVSControllerAPI.md'
        - 'AmazonPrimeAPI': 'AmazonPrimeAPI.md'
        - 'ApplicationAPI': 'ApplicationAPI.md'
        - 'BluetoothControlAPI': 'BluetoothControlAPI.md'
        - 'BluetoothRemoteControlAPI': 'BluetoothRemoteControlAPI.md'
        - 'BrowserAPI': 'BrowserAPI.md'
        - 'BrowserResourcesAPI': 'BrowserResourcesAPI.md'
        - 'BrowserSecurityAPI': 'BrowserSecurityAPI.md'
        - 'ButlerAPI': 'ButlerAPI.md'
        - 'CobaltAPI': 'CobaltAPI.md'
        - 'CompositorAPI': 'CompositorAPI.md'
        - 'ConnectionPropertiesAPI': 'ConnectionPropertiesAPI.md'
        - 'CustomerCareOperationsAPI': 'CustomerCareOperationsAPI.md'
        - 'DHCPServerAPI': 'DHCPServerAPI.md'
        - 'DIALServerAPI': 'DIALServerAPI.md'
        - 'DTVAPI': 'DTVAPI.md'
        - 'DeviceIdentificationAPI': 'DeviceIdentificationAPI.md'
        - 'DeviceInfoAPI': 'DeviceInfoAPI.md'
        - 'DisplayInfoAPI': 'DisplayInfoAPI.md'
        - 'DisplayPropertiesAPI': 'DisplayPropertiesAPI.md'
        - 'FirmwareControlAPI': 'FirmwareControlAPI.md'
        - 'GraphicsPropertiesAPI': 'GraphicsPropertiesAPI.md'
        - 'HDRPropertiesAPI': 'HDRPropertiesAPI.md'
        - 'IOConnectorAPI': 'IOConnectorAPI.md'
        - 'IOControlAPI': 'IOControlAPI.md'
        - 'InputSwitchAPI': 'InputSwitchAPI.md'
        - 'LanguageTagAPI': 'LanguageTagAPI.md'
        - 'LocationSyncAPI': 'LocationSyncAPI.md'
        - 'MessengerAPI': 'MessengerAPI.md'
        - 'MonitorAPI': 'MonitorAPI.md'
        - 'NetflixAPI': 'NetflixAPI.md'
        - 'NetworkControlAPI': 'NetworkControlAPI.md'
        - 'NetworkToolsAPI': 'NetworkToolsAPI.md'
        - 'OpenCDMiAPI': 'OpenCDMiAPI.md'
        - 'OutputAPI': 'OutputAPI.md'
        - 'PackagerAPI': 'PackagerAPI.md'
        - 'PerformanceMonitorAPI': 'PerformanceMonitorAPI.md'
        - 'PlayerInfoAPI': 'PlayerInfoAPI.md'
        - 'PlayerPropertiesAPI': 'PlayerPropertiesAPI.md'
        - 'PowerAPI': 'PowerAPI.md'
        - 'ProcessContainers': 'ProcessContainers.md'
        - 'ProvisioningAPI': 'ProvisioningAPI.md'
        - 'RemoteControlAPI': 'RemoteControlAPI.md'
        - 'SecureShellServerAPI': 'SecureShellServerAPI.md'
        - 'SecurityAgentAPI': 'SecurityAgentAPI.md'
        - 'SparkAPI': 'SparkAPI.md'
        - 'StateControlAPI': 'StateControlAPI.md'
        - 'StreamerAPI': 'StreamerAPI.md'
        - 'SubsystemControlAPI': 'SubsystemControlAPI.md'
        - 'SystemCommandsAPI': 'SystemCommandsAPI.md'
        - 'TestControllerAPI': 'TestControllerAPI.md'
        - 'TestUtilityAPI': 'TestUtilityAPI.md'
        - 'TestUtilityPlugin': 'TestUtilityPlugin.md'
        - 'TimeSyncAPI': 'TimeSyncAPI.md'
        - 'TraceControlAPI': 'TraceControlAPI.md'
        - 'VolumeControlAPI': 'VolumeControlAPI.md'
        - 'WebBrowserAPI': 'WebBrowserAPI.md'
        - 'WebKitBrowserAPI': 'WebKitBrowserAPI.md'
        - 'WiFiControlAPI': 'WiFiControlAPI.md'
    - 'Plugins doc':
        - 'BluetoothControlPlugin': 'BluetoothControlPlugin.md'
        - 'BluetoothRemoteControlPlugin': 'BluetoothRemoteControlPlugin.md'
        - 'CobaltPlugin': 'CobaltPlugin.md'
        - 'CommanderPlugin': 'CommanderPlugin.md'
        - 'CompositorPlugin': 'CompositorPlugin.md'
        - 'DHCPServerPlugin': 'DHCPServerPlugin.md'
        - 'DIALServerPlugin': 'DIALServerPlugin.md'
        - 'DTVPlugin': 'DTVPlugin.md'
        - 'DictionaryPlugin': 'DictionaryPlugin.md'
        - 'DisplayInfoPlugin': 'DisplayInfoPlugin.md'
        - 'FileTransferPlugin': 'FileTransferPlugin.md'
        - 'FirmwareControlPlugin': 'FirmwareControlPlugin.md'
        - 'IOConnectorPlugin': 'IOConnectorPlugin.md'
        - 'NetworkControlPlugin': 'NetworkControlPlugin.md'
        - 'PerformanceMonitorPlugin': 'PerformanceMonitorPlugin.md'
        - 'PlayerInfoPlugin': 'PlayerInfoPlugin.md'
        - 'PowerPlugin': 'PowerPlugin.md'
        - 'ProcessMonitorPlugin': 'ProcessMonitorPlugin.md'
        - 'RemoteControlPlugin': 'RemoteControlPlugin.md'
        - 'ResourceMonitorPlugin': 'ResourceMonitorPlugin.md'
        - 'SparkPlugin': 'SparkPlugin.md'
        - 'StreamerPlugin': 'StreamerPlugin.md'
        - 'SyslogExportPlugin': 'SyslogExportPlugin.md'
        - 'SystemCommandsPlugin': 'SystemCommandsPlugin.md'
        - 'TestUtilityPlugin': 'TestUtilityPlugin.md'
        - 'TimeSyncPlugin': 'TimeSyncPlugin.md'
        - 'VolumeControlPlugin': 'VolumeControlPlugin.md'
        - 'WebPAPlugin': 'WebPAPlugin.md'
        - 'WifiControlPlugin': 'WifiControlPlugin.md'
theme:
    name: windmill
    highlightjs: true
